### ISSUE TITLE
Changing the theme is not working

### ISSUE THREAD

**Issue by davelsio** [bouzidanas/react-reveal-slides#4]
Sorry about the issue rapid-fire! This is the last in a while, hopefully.

I tried chaning the `theme` prop to `beige` and `white`, but I don't think it's working. Once I remove the `data-background-color` from the default example, everything is white, but I've seen the default theme is actually `black`.

Using the `<link/>` tag as they mention in the docs does not work either, but this is most likely related to the bundler. Importing the theme directly at the App entry point works fine.

```js
import '../node_modules/reveal.js/dist/theme/beige.css';
```

**Comment by bouzidanas** [comment]
Hi @davelsan 

Until I make this an official component library, I am afraid you will have to import the theme you plan on using simply because the package doesnt include `reveal.js` and the CSS files found therein. That is why the install instructions has you installing `reveal.js` separately.

I will add this to the readme so people are aware.

Thanks for bringing this issue to light!
